---
language: node_js
node_js:
  - 10.14.1

sudo: required
addons:
  chrome: stable

dist: trusty

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=ember-lts-3.4
  - EMBER_TRY_SCENARIO=ember-lts-3.8
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true

before_install:
  - npm --version

script:
  - npm run lint-scripts
  # Usually, it’s ok to finish the test scenario without reverting
  # to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
